### PR TITLE
check-broken-packages: streamline and prettify; added verbose option

### PR DESCRIPTION
**Pull request by Optiligence**

### CODE REVIEW

**Comment by desbma** [comment]
What is the purpose of this change?
Can you explain how the output is different?

**Comment by Optiligence** [comment]
image
:arrow_down: 
image

**Comment by Optiligence** [comment]
image

**Comment by desbma** [comment]
Well I'm not convinced this is better.

This is more compact (sort of), differently colored, and moves the file information into a JSON output behind a verbose flag, which is a weird choice since the hook output will be read by humans.

So sorry, I'm not going to merge this as I prefer the current output as it is.

**Pull request closed without merging**
